/* This file is generated by 'makedefs' for reference purposes only. */
/* It is no longer used in the NetHack build. */

#if !defined(CROSSCOMPILE) || !defined(CROSSCOMPILE_TARGET)
#define BUILD_DATE "Sun Sep 13 17:06:56 2026"
#define BUILD_TIME (1789319216UL)

#define VERSION_NUMBER 0x05000000UL
#define VERSION_FEATURES 0x00060040UL
#define IGNORED_FEATURES 0x40080000UL
#define VERSION_SANITY1 0x211e117fUL

#define VERSION_STRING "5.0.0-0"
#define VERSION_ID \
 "Unix NetHack Version 5.0.0-0 post-release - last build Sun Sep 13 17:06:56 2026."
#define COPYRIGHT_BANNER_C \
 "         Version 5.0.0-0 Unix post-release, built Sun Sep 13 17:06:56 2026."
#endif /* !CROSSCOMPILE || !CROSSCOMPILE_TARGET */

