/* nhlua.h - generated by top Makefile */
#include "../lib/lua-5.4.8/src/lua.h"
ATTRNORETURN LUA_API int   (lua_error) (lua_State *L) NORETURN;
#include "../lib/lua-5.4.8/src/lualib.h"
#include "../lib/lua-5.4.8/src/lauxlib.h"
/*nhlua.h*/
